version: '3'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: python ./Student/manage.py makemigrations
    command: python ./Student/manage.py migrate
    command: python ./Student/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/Student
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
