# Generated by Django 4.2.7 on 2023-11-23 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_alter_teacher_teacher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.student'),
        ),
        migrations.AlterField(
            model_name='users',
            name='teacher_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.teacher'),
        ),
    ]
